import { generateHtml } from "./_template";
import type { PagesFunction } from "@cloudflare/workers-types";

export const onRequest: PagesFunction = async ({ request }) => {
  const origin = new URL(request.url).origin;
  const path = new URL(request.url).pathname;

  const config = {
    title: "YouTube to VTT Converter - Download WebVTT Subtitles from YouTube",
    description:
      "Free online tool to download YouTube subtitles as WebVTT (.vtt) files. Perfect for HTML5 video players, web applications, and online video platforms.",
    keywords: [
      "youtube to vtt",
      "youtube subtitle download vtt",
      "extract youtube subtitles vtt",
      "webvtt converter",
      "youtube webvtt",
      "html5 subtitles",
      "video caption download",
    ],
    heading: "YouTube to VTT Converter",
    subheading: "Download YouTube subtitles as WebVTT format for web video",
    content: `Extract YouTube subtitles and convert them to WebVTT (VTT) format. WebVTT is the modern standard for web video captions, designed specifically for HTML5 video elements and online streaming platforms.

VTT files are essential for web developers and content creators who want to add accessible, search-friendly captions to their videos. Our tool makes it easy to extract any YouTube video's subtitles in VTT format, whether they're manually uploaded or auto-generated by YouTube.`,
    ctaText: "Convert to VTT Now",
    relatedPages: [
      { title: "YouTube to SRT", href: "/youtube-to-srt" },
      { title: "YouTube to TXT", href: "/youtube-to-txt" },
      { title: "Batch Subtitle Downloader", href: "/tools/batch-downloader" },
    ],
    faqs: [
      {
        question: "What is WebVTT (VTT)?",
        answer:
          "WebVTT (Web Video Text Tracks) is the W3C standard for caption files on the web. It's designed specifically for HTML5 video and supports features like styling, positioning, and metadata that SRT doesn't have.",
      },
      {
        question: "How do I use VTT files on my website?",
        answer:
          "Add a track element to your HTML5 video: <track kind='subtitles' src='captions.vtt' srclang='en' label='English'>. Most modern browsers will automatically display the subtitles.",
      },
      {
        question: "What are the advantages of VTT over SRT?",
        answer:
          "VTT supports advanced features like text styling (color, font), positioning cues, chapter markers, and metadata. It's also the native format for web browsers and HTML5 video players.",
      },
      {
        question: "Can I convert VTT files to other formats?",
        answer:
          "Yes, VTT files can be easily converted to SRT or other formats using our other converter tools. The structure is similar, making conversion straightforward.",
      },
      {
        question: "Do video hosting platforms support VTT?",
        answer:
          "Most modern platforms support VTT, including YouTube, Vimeo, Brightcove, and self-hosted HTML5 video players. Check your platform's documentation for specific implementation details.",
      },
    ],
  };

  const html = generateHtml(config, origin, path);

  return new Response(html, {
    status: 200,
    headers: {
      "Content-Type": "text/html; charset=UTF-8",
      "Cache-Control": "public, max-age=86400",
    },
  });
};
